README.md

Update README for testing instructions

---

.travis.yml
scripts/ci_install_tiledb.sh

Setup Travis CI:
- Move tiledb installation to dedicated script for travis ci test.
Closes #2

Setup Travis CI

---

README.md
array.go
array_schema.go
attribute.go
compressor.go
config.go
context.go
context_test.go
dimension.go
doc.go
domain.go
group.go
query.go
version.go
vfs.go

Documentaiton improvemnts including
- function docstring changes
- minor example changes
- Compatiblity section in readme
- package introduction changes for godocs
Note: This does not include quickstart examples, I will add those after #16 in a seperate branch.

doc improvements

---

array.go
array_schema.go
array_schema_test.go
array_test.go
attribute.go
context.go
context_test.go
dimension.go
domain.go
domain_test.go
enums.go
group.go
query.go
query_test.go
vfs.go

This addresses some minor inconsistencies in the go api. Closes #16

Fix minor inconsistencies

---

array.go
array_schema.go

Add minor helper function from c++ api design,  Attributes() for ArraySchema. Closes #21

Add Attributes() function for ArraySchema

---

README.md

Update readme with details for v0.1.0 tagging. Closes #23

Update readme with details for v0.1.0 tagging

---

README.md
quickstart_dense_test.go

Update example in readme for dense quickstart

Update example in readme

---

array.go
array_schema.go
array_test.go
enums.go

Add support for encrypted arrays and array_open_at commands.

Add encryption support

---

query.go
query_test.go

Add support for fetching buffers from a query. Closes #34

Add support for get_buffer/buffer_var

---

README.md

Update readme for v0.2.0 tagging

Update readme for v0.2.0 tagging

---

array_schema.go

Array.Load*() should set finalizer for cleanup

Array.Load*() should set finalizer for cleanup

---

README.md
kv.go
kv_item.go
kv_iter.go
kv_schema.go
kv_test.go

This add basic KV support including for loop iterator support and a full testable example.

Add KV support. #37

---

array.go
kv.go

Update consolidation signatures. @jakebolewski are these api changes more or less finalized or do we expect further changes in the 1.5 cycle? If they are not finalized then we can hold off merging this.

Update consolidation signatures

---

vfs.go
vfs_test.go

Add vfs.DirSize()

---

go.mod
go.sum

Adds go.mod file in order to use go modules with go after 1.11
Closes #32

adds go.mod

---

.gitignore
examples/quickstart_dense_test.go
examples/quickstart_sparse_test.go

Examples use their own folder
Tests are enabled for examples
// Output: result, should be the last statement in a function having name starting with Example.

enables execution of quickstart examples in example folder

---

query.go
query_test.go

SetBuffer, SetBufferVar and SetCoordinates are amended to return a *uint64
This return value contains the effective buffer size
Contents of memory location is materialised after Submit() is called
Closes #51

Effective buffer size

---

examples/quickstart_dense_test.go
examples/quickstart_sparse_test.go
query.go
query_test.go

Implements ResultBufferElements
SetBufferVar additionally return offsetSize
Tests are added
Closes #52

Implements ResultBufferElements

---

.travis.yml
scripts/travis.gofmt.sh

adds go formatting to travis

---

README.md

adds version number, updates links and usage example

---

array.go
array_schema.go
attribute.go
context.go
dimension.go
domain.go
kv.go
kv_item.go
kv_schema.go
query.go
version.go
vfs.go

converts C.int and C.uint to C.int32_t and C.uint32_t respectively

---

array_schema.go
array_schema_test.go

Implement ArraySchema.Type(). Closes #68

Implement ArraySchema.Type()

---

array_schema.go

Restore ArraySchema MarshalJSON/UnmarshalJSON

Restore ArraySchema MarshalJSON/UnmarshalJSON

---

examples/config_test.go
scripts/ci_install_tiledb.sh

Update tiledb installation for ci with new serialization branch

Update tiledb installation for ci with new serialization branch

---

array_schema.go
buffer_list.go
buffer_list_test.go
enums.go
scripts/ci_install_tiledb.sh
serialize.go

Depends on core PR https://github.com/TileDB-Inc/TileDB/pull/1273

Serialization updates

---

serialize.go

Depends on https://github.com/TileDB-Inc/TileDB/pull/1279

Wrap max buffer size serialization C API.

---

serialize.go

Depends on https://github.com/TileDB-Inc/TileDB/pull/1281

Update for C API change to return new buffer object.

---

array.go
enums.go
query.go
serialize.go

Add datatype size function

---

examples/range_test.go
go.mod
query.go

Add support for range functions in TileDB-Go

---

README.md

Update README for 0.7.0

---

serialize.go

Binds API implemented in https://github.com/TileDB-Inc/TileDB/pull/1449

Bind array metadata serialization C API.

---

array.go
buffer.go
dimension.go
query.go

Handle 64bit integer for slice sizes

Handle 64bit integer for slice sizes

---

array.go

Add missing string_ascii and char types to array metadata

Metadata: Add missing string_ascii and char types

---

enums.go
query.go

Add new function for setting buffers directly with pointers. This is needed for users who wish to mmap buffers and set those for a query.

Add new function for setting buffers directly with pointers

---

scripts/ci_install_tiledb.sh

CI should use 1.7.7 for testing

CI should use 1.7.7 for testing

---

examples/range_test.go
scripts/ci_install_tiledb.sh
serialize.go

Add new (De)SerializeArrayNonEmptyDomainAllDimensions functions

Add new (De)SerializeArrayNonEmptyDomainAllDimensions functions

---

examples/writing_sparse_heter_dim_test.go
query.go

Should we drop `TILEDB_COORDS`?

Support hetereogeneus dimensions

---

array.go
array_test.go

Add nonEmptyDomain for fixed length dimensions

Add nonEmptyDomain for fixed length dimensions

---

query.go
query_test.go
scripts/ci_install_tiledb.sh

Add support for fetching variable length ranges

Add support for fetching variable length ranges

---

scripts/ci_install_tiledb.sh
serialize.go

Add support for serialization of est result size

Add support for serialization of est result size

---

array.go
clibrary.c
clibrary.h
examples/vacuum_test.go
go.mod
go.sum
vfs.go

Support vacuum

---

enums.go
go.mod
go.sum
query.go
templates/azure/jobs/test.yml

Usage:
https://github.com/TileDB-Inc/TileDB-REST-Prototype/pull/892

TILEDB_COORDS is supported in SetBuffer functions

---

array_schema.go
array_schema_test.go
query_test.go

Add allows dups getter and setter

---

clibrary.c
clibrary.h
enums.go
object.go
object_test.go

Adds support for object creation, getting type, moving and removing walk / ls functions

Support object management

---

vfs.go
vfs_test.go

This allows a VFS file handle to be used in functions which take one of the io package interfaces

Add support for io.Writer/Reader/Seeker in VFSfh

---

enums.go
object.go
object_test.go

Object is not a struct anymore, we rather handle object management by means of global functions in tiledb package

Fix object management

---

array.go

Add datetime support for non empty domain

Add datetime support for non empty domain

---

.github/scripts/install_tiledb_linux.sh
.github/scripts/install_tiledb_linux_debug.sh
.github/scripts/install_tiledb_macos.sh
config.go
query.go

Add config compare and query config getter

Add config compare and query config getter

---

context.go
query.go

Return an empty json object in bytes if tiledb does not error

Return empty json object bytes if empty

---

enums.go

Add support for TILEDB_BLOB type

Add support for TILEDB_BLOB type

---

.github/scripts/install_tiledb_linux.sh
.github/scripts/install_tiledb_linux_debug.sh
.github/scripts/install_tiledb_macos.sh
.github/scripts/install_tiledb_source_linux.sh
.github/scripts/install_tiledb_source_macos.sh
README.md
enums.go
fragment_info_test.go
group.go
query.go

Update to TileDB 2.10 and Support TILEDB_BOOL datatype.

Update to TileDB 2.10 and Support TILEDB_BOOL

---

query.go

Found in testing of https://github.com/TileDB-Inc/TileDB-Cloud-REST/releases/tag/2.10.0

More bool callsites

---

array.go
serialize.go

This adds missing SetConfig/Config for Array and SerializeArray APIs.

Add SetConfig/Config for Array and SerializeArray APIs

---

.github/workflows/tiledb-go.yml

Switch to prebuild TileDB for CI

Switch to prebuild TileDB for CI

---

.github/scripts/install_tiledb_linux.sh
.github/scripts/install_tiledb_linux_debug.sh
.github/scripts/install_tiledb_macos.sh
.github/scripts/install_tiledb_source_linux.sh
.github/scripts/install_tiledb_source_macos.sh
README.md
enums.go
fragment_info_test.go
query_test.go

Uses latest release TileDB 2.12.0

Support delete queries

---

group.go
group_test.go

Support https://tiledb-inc-tiledb.readthedocs-hosted.com/en/stable/c-api.html#c.tiledb_group_get_is_relative_uri_by_name

Add support tiledb_group_get_is_relative_uri_by_name

---

enums.go

Add query type from string

---

query.go

Remove deprecated usage of set query buffer functions. This is part 1 as we need to also migrate to the newer, better APIs for just `[Get|Set][Data|Offsets|Validity]Buffer`

Remove deprecated usage of set query buffer functions

---

enums.go
query_experimental.go
query_experimental_test.go

https://tiledb-inc-tiledb.readthedocs-hosted.com/en/stable/c-api.html#c.tiledb_query_get_status_details

Add support for tiledb_query_get_status_details

---

.github/scripts/install_tiledb_linux.sh
.github/scripts/install_tiledb_linux_debug.sh
.github/scripts/install_tiledb_macos.sh
.github/scripts/install_tiledb_source_linux.sh
.github/scripts/install_tiledb_source_macos.sh
group.go
group_test.go

Add bindings for delete group https://tiledb-inc-tiledb.readthedocs-hosted.com/en/stable/c%2B%2B-api.html#_CPPv4N6tiledb5Group12delete_groupERKNSt6stringEb

Sa/sc 28015/bindings for delete group

---

serialize.go

This is part of the new serialize path for query v3.

Add DeserializeQueryAndArray

---

.github/scripts/install_tiledb_linux.sh
.github/scripts/install_tiledb_linux_debug.sh
.github/scripts/install_tiledb_macos.sh
.github/scripts/install_tiledb_source_linux.sh
.github/scripts/install_tiledb_source_macos.sh
enumeration.go
enumeration_test.go

Support functionality for enumerations in TileDB 2.17.3

Support empty enumerations and extensions

---

.github/workflows/tiledb-go.yml

Update the TileDB core release for CI

Update CI to use 2.24.2

---

.github/workflows/tiledb-go.yml
README.md

Update to the latest TileDB release.

Update to TileDB 2.25.0

---

README.md
serialize.go

That request is being removed, more context in the REST PR here: https://github.com/TileDB-Inc/TileDB-Cloud-REST/pull/4852

Remove /max_buffer_sizes support

---

enumeration_experimental.go
enumeration_experimental_test.go
fragment_info.go
fragment_info_test.go
group.go
group_test.go
query_experimental.go

This wraps TileDB core APIs added in 2.27.0

Wrap TileDB 2.27.0 APIs

---

vfs.go
vfs_test.go

[SC-62257](https://app.shortcut.com/tiledb-inc/story/62257/implement-readat-in-vfsfh)

Add `VFSfh.ReadAt`.
