TileDB-Inc/TileDB-Go

- array.go
- array_schema.go
- array_schema_test.go
- array_test.go
- attribute.go
- attribute_test.go
- compressor.go
- config.go
- config_test.go
- context.go
- dimension.go
- dimension_test.go
- domain.go
- domain_test.go
- enums.go
- group.go
- group_test.go
- vfs.go
- vfs_test.go
This add Array Support, Array Schema, Dimension, Domain, Attribute, Group and adjust VFS to store context on struct.
Test coverage is only about 58% as query support is not implemented so any code paths that require data/non-empty arrays can't be tested via unit testing yet.
For functions which take void pointers to handle arrays of varies datatypes I've handled that by taking interface{}'s as a parameter to the function and then switching on the domain/dimension datatype to be able to convert the golang array to a void * in C.
Closes #7.
> Add Array Support

- README.md
- array.go
- array_schema.go
- enums.go
- query.go
- query_test.go
This add support for querying. A full example is given for the docs for NewQuery showing how to create and use an array with fixed and variable attributes.
Current limitations:
- SubmitAsync does not support a call back function. Support could be added for passing a void* in but this will require the end user to write a cgo function themselves. A good example is in the [cgo wiki article](https://github.com/golang/go/wiki/cgo#function-pointer-callbacks). I believe we'd need to document this and provide examples for users, so for now I've left off support.
- An alternative to use the callback from the c api is we could start a goroutine that polls the status and calls a user pass function when status is complete. This is simplier to an end user, but it would be nice to keep the …
> Query operation support

- stats.go
- stats_test.go
Add tiledb stats bindings including dump support to a given filepath and to stdout.
Closes #12
> Add tiledb stats bindings

- README.md
- doc.go
- quickstart_dense_test.go
- quickstart_sparse_test.go
This adds dense and sparse array quickstart examples. Documentation is also updated to link to the tiledb code quickstart guide.
Currently the examples are compiled but not run during tests. I will open a seperate issue to get the example run during unit testing.
> Add quickstart examples

- array.go
- array_test.go
Make URI public in array struct. This is helpful to users because after an array is created or loaded there currently is no way to get the URI from the Array Struct itself.
Closes #27
> Make URI public in array struct

- array.go
- quickstart_sparse_test.go
Problems are:
- the write query layout cannot be `ROW_MAJOR` for SparseArray
- `array.MaxBufferElements()` should return buffer bounds for coordinates too
This pull request fixes these issues by:
- modifying the write query layout to `TILEDB_UNORDERED` in the example code
- adding logic inside the `Array.MaxBufferElements` function  to handle coordinates
> SparseArray example does not work

- examples/async_test.go
- examples/config_test.go
- examples/encryption_test.go
- examples/error_check.go
- examples/errors_test.go
- examples/filters_test.go
- examples/fragments_consolidation_test.go
- examples/multi_attribute_test.go
- examples/quickstart_dense_test.go
- examples/reading_dense_layouts_test.go
- examples/reading_incomplete_test.go
- examples/reading_sparse_layouts_test.go
- examples/using_tiledb_stats_test.go
- examples/variable_length_test.go
- examples/vfs_test.go
- examples/writing_dense_global_expansion_test.go
- examples/writing_dense_global_test.go
- examples/writing_dense_multiple_test.go
- examples/writing_dense_padding_test.go
- examples/writing_dense_sparse_test.go
- examples/writing_sparse_global_test.go
- examples/writing_sparse_multiple_test.go
- vfs.go
This pull request is not ready to be merged
For reviewing the work so far
known facts:
- reading_incomplete should use ResultBufferElements
missing examples:
- fragments_consolidation
- map
- multi_attribute
- object
- quickstart_map
- using_tiledb_stats
- variable_length
> implements 18 out of 25 examples

- array.go
- array_schema.go
- attribute.go
- config.go
- context.go
- dimension.go
- domain.go
- enums.go
- filter.go
- filter_list.go
- group.go
- kv.go
- kv_item.go
- kv_iter.go
- kv_schema.go
- query.go
- stats.go
- version.go
- vfs.go
Running examples in ubuntu result in following error:
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libtiledb.so: undefined reference to `dlclose'
Adding dl in list of LDFLAGS resolves the issue
Tested on OSX and found to work as expected
> adds support for dl in LDFLAGS (CGO) for (ubuntu) linux

- array_schema.go
- query.go
The callers of these functions are responsible for freeing the given byte buffer. This allows for zero-copy during deserialization.
> Fix two instance of improper memory free for deserialization.

- query.go
In calls to query.Free() remove references to user buffers
> In calls to query.Free() remove references to user buffers

- query.go
This allows the core library REST tests to pass again.
> Add missing TILEDB_DATETIME_* cases for GetRange().

- array.go
- scripts/ci_install_tiledb.sh
Add function to fetch metadata with limited value. This is helpful to get a sample of the metadata if the values are very large.
> Add function to fetch metadata with limited value

- array.go
- dimension.go
- dimension_test.go
- examples/deserialize_sparse_layouts_test.go
- examples/reading_sparse_layouts_test.go
- examples/string_dim_test.go
- query.go
- serialize.go
ExampleStringDimArray follows https://github.com/TileDB-Inc/TileDB/blob/e26d52bc20996d9dd320032aa3049dd198c5c7fc/test/src/unit-cppapi-array.cc#L1120
> adds string dimension support

- context.go
TileDB core managed the c string and we don't need to free it.
> Don't free the c string in error messages

- query.go
This adds the new accessor of Array from the Query object added in TileDB 2.1
> Add support for query.Array()

- examples/reading_timestamp_test.go
When run, this test will create a 2D dense array, write data and metadata
to it multiple times keeping track of write timestamps, then read at specific
timestamp using array.OpenAt and prove correlation of timestamps to fragments
and metadata created /updated
> Add timestamp correlation test

- README.md
URLs are broken tried updating the ones I could find, however Quickstart link in Quick Links sections doesn't have an equivalent.
> Update README with proper installation link

- buffer.go
https://sentry.io/organizations/tiledb-inc/issues/2072733563/?environment=production&project=1273161&referrer=alert_email
> Context should not be nil in buffer creation

- query.go
This can happen if the user hasn't set any ranges.
> Handle empty size for GetRange w/ var length

- README.md
- attribute.go
- attribute_test.go
- examples/range_test.go
- examples/reading_incomplete_test.go
- examples/variable_length_test.go
- query.go
- query_test.go
- templates/azure/steps/install_tiledb_linux.yml
- templates/azure/steps/install_tiledb_macos.yml
This adds new functionality for nullable attributes. This includes:
`Attribute.SetNullable(nullable bool) err`
`Attribute.Nullable() (bool, err)`
`Query.SetBufferNullableUnsafe(attribute string, buffer unsafe.Pointer, bufferSize uint64, bufferValidity unsafe.Pointer, bufferValiditySize uint64) (*uint64, *uint64, error)`
`Query.SetBufferNullable(attributeOrDimension string, buffer interface{}, bufferValidity []uint8) (*uint64, *uint64, error)`
`Query.SetBufferVarNullableUnsafe(attribute string, offset unsafe.Pointer, offsetSize uint64, buffer unsafe.Pointer, bufferSize uint64, bufferValidity unsafe.Pointer, bufferValiditySize uint64) (*uint64, *uint64, *uint64, error)`
`Query.SetBufferVarNullable(attributeOrDimension string, offset []uint64, buffer interface{}, bufferValidity []uint8) …
> Add support for TileDB 2.2. Nulls

- array.go
- fragment_info.go
- fragment_info_test.go
Supports:
```
TILEDB_EXPORT int32_t tiledb_fragment_info_alloc(
tiledb_ctx_t* ctx,
const char* array_uri,
tiledb_fragment_info_t** fragment_info);
TILEDB_EXPORT void tiledb_fragment_info_free(
tiledb_fragment_info_t** fragment_info);
TILEDB_EXPORT int32_t tiledb_fragment_info_load(
tiledb_ctx_t* ctx, tiledb_fragment_info_t* fragment_info);
TILEDB_EXPORT int32_t tiledb_fragment_info_load_with_key(
tiledb_ctx_t* ctx,
tiledb_fragment_info_t* fragment_info,
tiledb_encryption_type_t encryption_type,
const void* encryption_key,
uint32_t key_length);
TILEDB_EXPORT int32_t tiledb_fragment_info_get_fragment_num(
tiledb_ctx_t* ctx,
tiledb_fragment_info_t* fragment_info,
uint32_t* fragment_num);
TILEDB_EXPORT int32_t tiledb_fragment_info_get_fragment_uri(
tiledb_ctx_t* ctx,
tiledb_fragment_info_t* …
```
> Add support for fragment info apis

- .github/scripts/install_tiledb_linux.sh
- .github/scripts/install_tiledb_macos.sh
- fragment_info_test.go
`FragmentInfo` can be queried for version, which can change as TileDB Core evolves. This means we need to test fragment info version produced in our tests to be correct against TileDB Core version, TileDB-Go is used each time, for example Fragmet Info version `7` was true for TileDB Core versions `2.2.1`, `2.2.2`.
In this PR we relax the condition and ask for fragment info version to be greater than 0 to accommodate for future updates from TileDB Core
https://github.com/TileDB-Inc/TileDB-Go/issues/154
> Test fragment info have version greater than zero

- examples/range_test.go
- query.go
- query_test.go
Adds support for:
```
int32_t tiledb_query_add_range_by_name(
tiledb_ctx_t* ctx,
tiledb_query_t* query,
const char* dim_name,
const void* start,
const void* end,
const void* stride);
TILEDB_EXPORT int32_t tiledb_query_add_range_var_by_name(
tiledb_ctx_t* ctx,
tiledb_query_t* query,
const char* dim_name,
const void* start,
uint64_t start_size,
const void* end,
uint64_t end_size);
TILEDB_EXPORT int32_t tiledb_query_get_range_num_from_name(
tiledb_ctx_t* ctx,
const tiledb_query_t* query,
const char* dim_name,
uint64_t* range_num);
TILEDB_EXPORT int32_t tiledb_query_get_range_from_name(
tiledb_ctx_t* ctx,
const tiledb_query_t* query,
const char* dim_name,
uint64_t range_idx,
const void** start,
const void** end,
const void** stride);
TILEDB_EXPORT int32_t …
```
> Add Get Range By Name support

- stats.go
- stats_test.go
This allows returning TileDB Statistics as a string and also additional functions for returning or dumping the raw statistics which are in JSON form.
> Add additional stats functions

- query.go
- query_test.go
This allows setting the config on a query object.
> Add `Query.SetConfig()`

- array.go
- query_test.go
Adds `NonEmptyDomainMap` which returns a map[string]interface{} where key is the
dimension name and value is the non empty domain for the given dimension or
the empty interface. It covers both var-sized and non-var-sized dimensions
> Builds map of non-empty domains for all dimensions in array

- README.md
The golang flag parser does not allow single-character options to be
smashed together, so separate the `-v` and `-t` in the instructions.
> Fix flag passing in README

- array.go
- array_schema.go
- domain.go
- examples_lib/writing_sparse_global.go
- examples_lib/writing_sparse_multiple.go
- fragment_info.go
- object.go
- query.go
Uses the same naming schema for the tiledb context type
> Use consistent naming for a tiledb context type

- context.go
- context_test.go
- query.go
- query_test.go
Returns results as a string while the Stats API contract is TBD. I expect we should return a struct in the future. Current example:
```
{
"timers": {
"Context.StorageManager.Query.Reader.unfilter_coord_tiles.sum": 0.000418128,
"Context.StorageManager.Query.Reader.unfilter_coord_tiles.avg": 0.000139376,
"Context.StorageManager.Query.Reader.unfilter_attr_tiles.sum": 0.000282641,
"Context.StorageManager.Query.Reader.unfilter_attr_tiles.avg": 0.000282641,
"Context.StorageManager.Query.Reader.read.sum": 0.00506632,
"Context.StorageManager.Query.Reader.read.avg": 0.00506632,
"Context.StorageManager.Query.Reader.init_state.sum": 0.000134505,
"Context.StorageManager.Query.Reader.init_state.avg": 0.000134505,
"Context.StorageManager.Query.Reader.copy_var_attr_values.sum": 6.4168e-05, …
```
> Add query and context stats

- context.go
- context_test.go
Also updates errors in context.go to use `%w` to wrap the error cause
when appropriate.
> Add NewContextFromMap, a shortcut for creating a Context from settings.

- array.go
- array_schema.go
- attribute.go
- buffer.go
- buffer_list.go
- config.go
- config_iter.go
- context.go
- dimension.go
- domain.go
- filter.go
- filter_list.go
- fragment_info.go
- query.go
- query_condition.go
- vfs.go
This change replaces the doc comments for all the Free functions with
a more descriptive one that addresses that (a) it is idempotent and
(b) it is called automatically.
> Expand documentation of all x.Free() functions.

- serialize.go
- serialize_test.go
https://github.com/TileDB-Inc/TileDB/blob/ecfb3c629a8f3cf9377661afa94bedd0f26ec26f/tiledb/sm/c_api/tiledb.cc#L5275-L5290
In tiledb_deserialize_array_schema, `*array_schema` will be
unconditionally set to a newly-allocated address. If an error later
occurs, `*array_schema` remains at that value, but the memory that it
points to *has already been freed*. That means that, on the Go side,
it sees the `ArraySchema.tiledbArraySchema` as a non-nil pointer,
so when it goes to free it in `ArraySchema.Free`, the memory will be
freed again.
This change works around that by only adding the finalizer *after*
it is verified that there was no error.
---
Editor’s notes:
- It would be good to add tests on the other functions but I don’t know of a reliable way to get them to error out unlike trying to …
> Fix segfault when attempting to DeserializeArraySchema invalid data.

- .github/workflows/tiledb-go.yml
Our go.mod file says we require Go 1.15, and now that Go 1.16 is out,
v1.14 is no longer supported.
> Update CI workflows to only cover supported versions of Go.

- .github/workflows/tiledb-go.yml
- cmd/tiledb-go-examples/asan_off.go
- cmd/tiledb-go-examples/asan_on.go
- cmd/tiledb-go-examples/main.go
This re-enables running the ASAN build of the TileDB-Go examples using the `asan` build tag. It also adds a cache for the Go dependencies. (This pattern can later be followed to cache the built TileDB core library to avoid needing to build it from source every time.)
> re-enable ASAN run and improve build/test workflow

- .github/scripts/install_tiledb_source_linux.sh
- .github/scripts/install_tiledb_source_macos.sh
- examples/vacuum_test.go
Issue with fragments is resolved in TileDB Core 2.4, test passes
> Removes not experimental tag from vacuum test

- README.md
(I know it's linked from the status, but that's too subtle for me)
> Add explicit link to GoDoc

- context.go
- context_test.go
Adds the ctx_cancel_tasks Go wrapper func. This can be used to cancel any long running tasks associated with the context. Common use case would likely include long running queries that have exceeded a configured timeout.
> Add cancel tasks on context func

- array.go
- array_schema.go
- array_schema_evolution.go
- attribute.go
- buffer.go
- buffer_list.go
- dimension.go
- domain.go
- filter.go
- filter_list.go
- fragment_info.go
- query.go
- query_condition.go
- vfs.go
Exposes the internal tiledb context used for initialization for a Getter. Guards against setting by keeping the field unexported.
> Add getters for internal tiledb ctx

- .github/scripts/install_tiledb_linux.sh
- .github/scripts/install_tiledb_linux_debug.sh
- .github/scripts/install_tiledb_macos.sh
- .github/scripts/install_tiledb_source_linux.sh
- .github/scripts/install_tiledb_source_macos.sh
- .github/workflows/tiledb-go.yml
- clibrary.c
- clibrary.h
- vfs.go
- vfs_test.go
Changes in Github Actions:
- Use of `macos-11`
- Use of TileDB Core `2.5.3` instead of `2.5.2`
> Support VFS Ls

- vfs.go
Protects against a byte slice unsafe.Pointer panic when no data is passed to the function
> Protect against empty byte writes

- array.go
- enums.go
Removes error case for when a nil pointer is returned for a given metadata value because it is empty. Removal of the check necessitated getting back a zero value from GetValue. Empty values occur even though they're abnormal.
> Do not error for empty metadata value

- array.go
Char arrays come in as a slice of bytes, this marshals them as strings
> Marshal []bytes as string for array metadata values

- array_schema.go
- array_schema_evolution_test.go
- buffer.go
- buffer_test.go
- group.go
- query_test.go
- serialize.go
- serialize_array_schema_evolution.go
Adds serialization helper funcs on a buffer. 
Handles:
- Trim of null terminated core buffers for JSON
- Maintains null terminator for capnp
- Creates copy of buffers to limit issues with Go GC and buffer collection
> Add serialization helper func, create copy of bytes to prevent gc

- buffer.go
- go.mod
- go.sum
- vendor/go4.org/unsafe/assume-no-moving-gc/LICENSE
- vendor/go4.org/unsafe/assume-no-moving-gc/README.md
- vendor/go4.org/unsafe/assume-no-moving-gc/assume-no-moving-gc.go
- vendor/go4.org/unsafe/assume-no-moving-gc/untested.go
- vendor/modules.txt
Large parts of this library rely on the fact that the Go GC does not
move objects when collecting them (compare to, e.g. the HotSpot JVM GC,
which does move objects extensively). This adds a combination of
documentation and assertion of this fact.
> Add assertion/documentation that we rely on non-moving GC.

- array.go
- array_schema.go
- array_schema_evolution.go
- attribute.go
- buffer.go
- buffer_list.go
- config.go
- config_iter.go
- context.go
- dimension.go
- domain.go
- filestore.go
- filter.go
- filter_list.go
- fragment_info.go
- group.go
- memory.go
- query.go
- query_condition.go
- serialize.go
- serialize_array_schema_evolution.go
- vfs.go
This centralizes all the calls to `runtime.SetFinalizer` into one place,
and documents exactly where that function should be called. This reduces
repetition and hopefully makes things less error-prone.
> Pulls `runtime.SetFinalizer` calls into a `freeOnGC` function.

- .github/scripts/install_tiledb_linux.sh
- .github/scripts/install_tiledb_linux_debug.sh
- .github/scripts/install_tiledb_macos.sh
- .github/scripts/install_tiledb_source_linux.sh
- .github/scripts/install_tiledb_source_macos.sh
- query_experimental.go
Add support for `tiledb_query_get_relevant_fragment_num` via `Query.RelevantFragmentCount` in a new experimental file.
This requires TileDB 2.10.4 that is pending release.
> Add support for tiledb_query_get_relevant_fragment_num

- array.go
- array_test.go
- enums.go
- group.go
This allows us to support nulls in the strings. TileDB does not use null delimiters for any data, but the conversion from "C" to "Go" was treating nulls as delimiters. This solves this by using the size give by the core.
> Replace C.GoString with C.GoStringN where applicable

- buffer.go
- common.go
- memory.go
This creates byteBuffer, a safer way to handle buffers that are passed to and from C. It keeps track of its own address and uses that to resolve indices relative to itself, so that the Go garbage collector can always keep track of the memory that is in use.
> Use a safe(r) internal byte-storage type in Buffer.

- context.go
If a config is passed in we need to keep it alive to ensure the config isn't garbage collected while it is being used in the cgo call for tiledb_ctx_alloc.
> Keepalive config for context creation

- array.go
This ensure the consolidation/vacuum configs are not gc'ed during the Cgo call to TileDB.
> Add keepalive to config for consolidate/vacuum

- enumeration.go
- enumeration_test.go
The TileDB enumerations PR can be found at https://github.com/TileDB-Inc/TileDB/pull/4051
A usage example can be found at https://github.com/TileDB-Inc/TileDB/blob/dev/examples/cpp_api/enumerations.cc
> Add enumerations

- enums.go
- query.go
- range.go
- range_test.go
- reflection.go
- subarray.go
- subarray_test.go
This adds support for the TileDB core Subarray API for queries, see https://tiledb-inc-tiledb.readthedocs-hosted.com/en/stable/c-api.html#subarray
The API uses go generics to avoid casts and passing type unsafe `interface{}` values. Check the tests for usage examples.
> Support the TileDB core Subarray API for queries

- array.go
- array_schema.go
- array_schema_evolution.go
- attribute.go
- buffer.go
- buffer_list.go
- cgo_flags.go
- config.go
- config_iter.go
- context.go
- dimension.go
- dimension_label.go
- dimension_label_unimplemented.go
- domain.go
- enums.go
- filestore.go
- filter.go
- filter_list.go
- fragment_info.go
- group.go
- object.go
- query.go
- query_condition.go
- query_experimental.go
- serialize.go
- serialize_array_schema_evolution.go
- stats.go
- subarray.go
- version.go
- vfs.go
1. cgo concatenates all flags in a package:
> All the cgo CPPFLAGS and CFLAGS directives in a package are concatenated and used to compile C files in that package. (https://pkg.go.dev/cmd/cgo)
So we can put them in a standalone file and remove duplication, which
causes linker warnings on some platforms.
2. Note that `cgo_flags.go` must:
- start with `package tiledb`
- the cgo comments must be immediately followed by `import "C"`
(or else they are ignored)
> Deduplicate cgo flags

- .github/scripts/install_tiledb_linux.sh
- .github/scripts/install_tiledb_linux_debug.sh
- .github/scripts/install_tiledb_macos.sh
- .github/scripts/install_tiledb_source_linux.sh
- .github/scripts/install_tiledb_source_macos.sh
- README.md
- array.go
- array_test.go
- serialize.go
This implements the 2 new endpoints `tiledb_array_delete_fragments_v2` and `tiledb_array_delete_fragments_list` for the upcoming TileDB core 2.18.0
> New delete fragments endpoints

- .github/scripts/install_tiledb_linux.sh
- .github/scripts/install_tiledb_linux_debug.sh
- .github/scripts/install_tiledb_macos.sh
- .github/scripts/install_tiledb_source_linux.sh
- .github/scripts/install_tiledb_source_macos.sh
- README.md
This is a release to support TileDB 2.19.0. Core contains new experimental functionality like consolidation and query plans but there are no bindings here. These will be included in the next release with TileDB 2.20 support.
> Sa/release 0.25.0

- .github/scripts/install_tiledb_macos.sh
Our macOS job's tar often fails with the error message "Can't restore
time".  The following issue's detective work revealed that the problem
is caused by Apple's tar choking on extracting sparse files:
https://github.com/actions/runner-images/issues/2619
This commit adds the `-S` flag to tar, which fixes the problem.
> Add tar flag to fix corrupt macOS workflow.

- .github/workflows/tiledb-go.yml
- README.md
- enumeration_test.go
- enums.go
- query.go
This PR adds support for the two new datatypes `TILEDB_GEOM_WKB` and `TILEDB_GEOM_WKT` that were added as part of the minor version bump to TileDB 2.21.0.
The PR also upgrades TileDB-Go to 2.21.0.
I _think_ that's all we need to support 2.21.0 but would be great to get a second pair of eyes on this.
> Support and upgrade to TileDB 2.21.0.

- .github/workflows/tiledb-go.yml
- README.md
Go through the release ritual of updating to the latest TileDB release.
> Update to TileDB v2.22.0.

- group_experimental.go
- query.go
- string.go
[SC-45987](https://app.shortcut.com/tiledb-inc/story/45987/tiledb-go-migrate-away-from-deprecated-tiledb-c-apis)
This PR updates TileDB-Go's usage of deprecated C APIs. The first commit migrates the `Group.GetMember***` functions to use `tiledb_group_get_member_by_(index|name)_v2`, while also adding code to work with TileDB string handles. The second commit deprecates `Query.SubmitAsync`, whose underlying C API has been deprecated since 2.15.
After that, the only deprecated C APIs used by TileDB-Go are inside deprecated Go APIs.
> Migrate away from deprecated TileDB C APIs.

- .github/workflows/tiledb-go.yml
- README.md
...which was released on May 8, 2024:
https://github.com/TileDB-Inc/TileDB/releases/tag/2.23.0
> Update to TileDB 0.23.0.

- README.md
TileDB's dev branch [contains a PR](https://github.com/TileDB-Inc/TileDB/pull/4961) that breaks compatibility with TileDB-Go. The problem will be fixed in the next release but in the meanwhile we should warn users to not use TileDB-Go with TileDB's dev branch.
> Add warning about temporary incompatibility.

- .github/scripts/install_tiledb_linux_debug.sh
- .github/scripts/install_tiledb_source_linux.sh
- .github/scripts/install_tiledb_source_macos.sh
Preparation for SC-36913
This PR updates the shell scripts to use the `install-tiledb` target to build and install TileDB, instead of invoking `make` twice – once in the build directory, and once in the `tiledb` subdirectory.
TileDB is going to remove the superbuild and become a single CMake project without the `tiledb` subdirectory, and with this PR the Go API will be prepared for this.
> Prepare for TileDB's superbuild removal.

- dimension.go
`tiledb_dimension_get_domain` does not copy the bytes from the domain into the passed-in pointer; instead it uses the passed-in pointer as an out value, which it writes to point to the memory that it owns. This means that we can eliminate our allocating code. At the same time, we also use generics to reduce a bunch of duplication.
---
A little bit of stuff I figured is a good thing for a Friday fix-it.
> Simplify memory handling in dimension.go with generics.

- common.go
- enums.go
- memory.go
Yet another step on the road of consolidating things and making memory handling more straightforward. This stuff eventually helps lead to removing the deprecation warnings that show up on every compile, I promise.
> Shorten datatype conversions in enums.go with generics.

- .github/workflows/tiledb-go.yml
No changes are necessary other than updating the version that CI uses.
> Update CI to use 2.24.1.

- .github/CODEOWNERS
Add CODEOWNERS for automatic reviewer tagging. (anyone with merge rights is encouraged
to review and approve PRs they understand)
> Add automatic reviewer tagging via CODEOWNERS

- common.go
- enums.go
- memory.go
Reverts TileDB-Inc/TileDB-Go#321
Temporary revert as this likely introduced a regression
> Revert "Shorten datatype conversions in enums.go with generics."

- dimension.go
Reverts TileDB-Inc/TileDB-Go#248
Temporary revert as this likely introduced a regression
> Revert "Simplify memory handling in dimension.go with generics."

- go.mod
Adds a module retraction for a regression in which a panic is triggered when referencing enums
> Add go mod retraction for v0.30.1

- array_test.go
- common.go
- dimension.go
- enums.go
- memory.go
This reverts #331 and #330, thus reintroducing #248 and #321.
The issue in those changes was that when attempting to copy a null/zero-length string, we would do something like `C.GoStringN(nil, 0)` or maybe `C.GoStringN(someInvalidAddress, 0)`. Either of those should (in theory) give you a zero-length string, but in practice we want to manually check (as the code did before I removed that check). The check remained present in the *other* uses, since they all had an equivalent check before their copying operation in `getValueInternal`.
This change is also currently running through a server-side test suite.
> Reapply simplification of memory handling with generics.

- array.go
- array_experimental.go
- array_experimental_test.go
- common.go
This adds the  `tiledb_array_consolidate_fragments` binding required for cloud fragment list consolidation.
CI will fail on this PR until https://github.com/TileDB-Inc/TileDB/pull/5135 is merged and backported to the core version in use by TileDB-Go.
> Add binding for tiledb_array_consolidate_fragments.

- array.go
- dimension.go
- dimension_label_experimental.go
- filestore_experimental.go
- serialize.go
- subarray.go
- vfs.go
Since replacing other uses of the `&someSlice[0]` construction with `slicePtr(someSlice)` has already saved us from errors, this change replaces the remaining uses, for more robustness and easier reading.
> Replace all slice-pointer use with slicePtr function.

- array.go
- array_test.go
Our existing WithStartTimestamp/WithEndTimestamp opening options only allow passing in a millisecond timestamp. This change adds the option to pass these timestamps in the format of a time.Time, making it safer from users accidentally passing in the wrong unit of measurement.
> Add open options to set timestamp with a time.Time.

- array.go
- query.go
This makes it a bit more convenient to do a few things:
- You can now allocate a new Array and provide a nil Context and a new (empty) Context will be created for you.
- When you create a new Query from an Array, you can provide a nil context and the array’s context will be used.
---
Another thing I ran into while working on stuff, which might make things a little more convenient for the majority of these constructor functions.
> Allow nil contexts to be passed when they can be inferred.

- array_experimental_test.go
The tests were skipped pending an upgrade to TileDB 2.25.0. I also modified the test to run with absolute and relative fragment URIs.
> Enable fragment list consolidation tests.

- .github/workflows/tiledb-go.yml
- array.go
- context.go
- dimension_label_experimental.go
- examples_lib/encryption.go
- examples_lib/filters.go
- examples_lib/quickstart_sparse.go
- examples_lib/vacuum.go
- examples_lib/writing_dense_global_expansion.go
- examples_lib/writing_sparse_multiple.go
- query.go
- query_test.go
- reflection.go
- subarray.go
- vfs.go
This fixes ASAN failures seen on CI, it looks like they were due to missing calls to `Free()` either in the example code or internal definitions.
If this looks correct I can follow up and look for similar errors. At the moment this only fixes those reported by `build_with_sanitizer_and_run.sh` so ASAN CI should pass now, but I would expect there's other similar errors that are not covered by the examples.
> Fix ASAN failures.

- .github/scripts/install_tiledb_macos.sh
- .github/workflows/tiledb-go.yml
In particular:
* Test Go 1.23.
* Use the latest version for our Ubuntu and macOS runners.
* Remove the cache action as it's no longer needed.
* A few fixes for the test to run on new macOS instances.
I recommend reviewing the PR commit by commit.
> Make various improvements to our GitHub workflow

- .github/workflows/tiledb-go.yml
- README.md
Update to the latest TileDB release.
> Update to TileDB 2.26.0

- .github/workflows/tiledb-go.yml
Update the TileDB core release for CI
> Update CI to use 2.26.1

- .github/CODEOWNERS
Going forward, this will allow for more consistent reviewer management.
> Replace individual accounts with team.

- buffer.go
So far, we would cast a uint64 to a int32 but that may result in an integer overflow. At this point, GoBytes does not seem to support buffers this large, so the next best thing to do is return an error if the given buffer is too large.
---
According to the test below, this check works correctly. I'd rather not add this (or a similar) test because it relies on allocating a 2 GiB buffer.
```go
func TestBufferOverflow(t *testing.T) {
context, err := NewContext(nil)
require.NoError(t, err)
buffer, err := NewBuffer(context)
require.NoError(t, err)
require.NoError(t, buffer.SetBuffer(make([]byte, math.MaxInt32+10)))
buffer.data = nil
c, err := buffer.dataCopy()
t.Logf("buf len: %d", len(c))
t.Log(err)
}
```
> Return an error if the buffer is too large.

- .github/workflows/tiledb-go.yml
- README.md
This updates TileDB-Go to use the latest TileDB 2.27.0
> Update to TileDB 2.27.0.

- .github/workflows/tiledb-go.yml
- buffer.go
- go.mod
This updates to use Go 1.22, since Go 1.21 [reached EOL 4 months ago](https://endoflife.date/go).
> Update to Go 1.22.

- .github/workflows/tiledb-go.yml
- .golangci.yml
- array.go
- array_experimental.go
- array_schema.go
- array_schema_evolution_experimental.go
- attribute.go
- buffer.go
- buffer_list.go
- config.go
- config_iter.go
- context.go
- dimension.go
- dimension_label_experimental.go
- domain.go
- enumeration_experimental.go
- filestore_experimental.go
- filter.go
- filter_list.go
- fragment_info.go
- group.go
- memory.go
- object.go
- query.go
- query_condition.go
- query_experimental.go
- serialize.go
- subarray.go
- vfs.go
[SC-58351](https://app.shortcut.com/tiledb-inc/story/58351)
[SC-62492](https://app.shortcut.com/tiledb-inc/story/62492)
* We use `runtime.KeepAlive` to keep the finalizers of TileDB objects from being called during each cgo call.
* The keepalives are put right after the call, ordered by the object's appearence in the C function's parameters.
* If a C API returns pointers to C-owned memory, these are documented, and the keepalives are put right after the last use of that pointer.
* If a variable does not need a keepalive when using it or passing it to C, that fact is documented.
* We use the `runtime.Pinner` type to pin memory held long-term by C, in a well-defined way.
* Unpinning happens in the `Free()` function, after the C handle is freed.
* This makes us (to the best of my knowledge) …
> Improve memory safety of cgo interop code.

- .github/workflows/tiledb-go.yml
Update CI to use the new `libtiledb` minor release.
> Update CI to use 2.27.2

- .github/workflows/tiledb-go.yml
- README.md
- array_schema_experimental.go
- array_schema_experimental_test.go
- range.go
- stats.go
- stats_test.go
- vfs.go
- vfs_test.go
This updates to TileDB 2.28.0 and wraps new APIs added for this release.
> Update to TileDB 2.28.0

- array.go
- group.go
- group_test.go
This PR fixes [ENG-98](https://linear.app/tiledb/issue/ENG-98/add-support-for-group-metadata-in-tiledb-go).
While working with asset metadata and specifically group metadata i noticed that we could add some functions in `group.go` so that we can have a similar pattern on how to interact with core metadata with arrays and groups. All the infra and core support is there we were just missing the functions from this PR.
> add group metadata functions with similar pattern that arrays use

- group.go
A group might have a name specified or not and we shouldn't fail if the name returned by `tiledb_group_get_member_by_index_v2` is `nil`.
> Fix error when a member (optional) name is empty
